<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Switchyard.Messaging\Switchyard.Messaging.csproj" />
  </ItemGroup>
</Project>
