// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchyard.Payments.Infrastructure.Persistence;

#nullable disable

namespace Switchyard.Payments.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260919155357_AddPaymentAuthorisationReconciliation")]
    partial class AddPaymentAuthorisationReconciliation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Switchyard.Payments.Infrastructure.Persistence.PaymentAuthorisationAttemptRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset?>("LastReconciledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reconciled_at_utc");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_idempotency_key");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_reference");

                    b.Property<int>("ReconciliationAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reconciliation_attempt_count");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("RequestId")
                        .HasName("pk_payments_authorisation_attempts");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_authorisation_payment");

                    b.HasIndex("ProviderIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_authorisation_provider_key");

                    b.HasIndex("ProviderReference")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_authorisation_provider_reference");

                    b.ToTable("authorisation_attempts", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_authorisation_pending_not_reconciled", "status <> 0 OR reconciliation_attempt_count = 0");

                            t.HasCheckConstraint("ck_payments_authorisation_provider_key", "btrim(provider_idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_payments_authorisation_provider_reference", "provider_reference IS NULL OR btrim(provider_reference) <> ''");

                            t.HasCheckConstraint("ck_payments_authorisation_reconciliation_count", "reconciliation_attempt_count >= 0");

                            t.HasCheckConstraint("ck_payments_authorisation_reconciliation_shape", "(reconciliation_attempt_count = 0 AND last_reconciled_at_utc IS NULL) OR (reconciliation_attempt_count > 0 AND last_reconciled_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_payments_authorisation_reconciliation_time", "last_reconciled_at_utc IS NULL OR last_reconciled_at_utc >= requested_at_utc");

                            t.HasCheckConstraint("ck_payments_authorisation_shape", "(status = 0 AND provider_reference IS NULL AND resolved_at_utc IS NULL) OR (status IN (1, 2) AND provider_reference IS NOT NULL AND resolved_at_utc IS NOT NULL) OR (status = 3 AND resolved_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_payments_authorisation_status", "status IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("ck_payments_authorisation_time", "resolved_at_utc IS NULL OR resolved_at_utc >= requested_at_utc");
                        });
                });

            modelBuilder.Entity("Switchyard.Payments.Infrastructure.Persistence.PaymentIntentRecord", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("AuthorisationResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorisation_resolved_at_utc");

                    b.Property<int>("AuthorisationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("authorisation_status");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments_payment_intents");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_payment_intent_order");

                    b.ToTable("payment_intents", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_intent_amount", "amount > 0");

                            t.HasCheckConstraint("ck_payments_intent_authorisation_shape", "(authorisation_status = 0 AND authorisation_resolved_at_utc IS NULL) OR (authorisation_status IN (1, 2, 3) AND authorisation_resolved_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_payments_intent_authorisation_status", "authorisation_status IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("ck_payments_intent_authorisation_time", "authorisation_resolved_at_utc IS NULL OR authorisation_resolved_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_payments_intent_currency", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("Switchyard.Payments.Infrastructure.Persistence.PaymentAuthorisationAttemptRecord", b =>
                {
                    b.HasOne("Switchyard.Payments.Infrastructure.Persistence.PaymentIntentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_authorisation_payment_intent");
                });
#pragma warning restore 612, 618
        }
    }
}
