// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchyard.Ordering.Infrastructure.Persistence;

#nullable disable

namespace Switchyard.Ordering.Infrastructure.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260918073204_AddOrderRequestIdempotency")]
    partial class AddOrderRequestIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_sequence", "ordering")
                .StartsAt(100000L);

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderLineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_amount");

                    b.HasKey("Id")
                        .HasName("pk_order_lines");

                    b.HasIndex("OrderId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_order_lines_order_id_position");

                    b.ToTable("order_lines", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_lines_currency", "char_length(currency) = 3");

                            t.HasCheckConstraint("ck_order_lines_position", "position >= 0");

                            t.HasCheckConstraint("ck_order_lines_product_name_not_blank", "btrim(product_name) <> ''");

                            t.HasCheckConstraint("ck_order_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_order_lines_sku_not_blank", "btrim(sku_code) <> ''");

                            t.HasCheckConstraint("ck_order_lines_unit_price", "unit_price_amount >= 0");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_order_number");

                    b.ToTable("orders", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_orders_order_number_not_blank", "btrim(order_number) <> ''");

                            t.HasCheckConstraint("ck_orders_status", "status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRequestRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("IdempotencyKey")
                        .HasName("pk_order_requests");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_order_requests_order_id");

                    b.ToTable("order_requests", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_requests_idempotency_key_not_blank", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_order_requests_request_fingerprint", "char_length(request_fingerprint) = 64");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderLineRecord", b =>
                {
                    b.HasOne("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRequestRecord", b =>
                {
                    b.HasOne("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", null)
                        .WithOne()
                        .HasForeignKey("Switchyard.Ordering.Infrastructure.Persistence.OrderRequestRecord", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
