// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchyard.Ordering.Infrastructure.Persistence;

#nullable disable

namespace Switchyard.Ordering.Infrastructure.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260919213750_AddOrderingInbox")]
    partial class AddOrderingInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_sequence", "ordering")
                .StartsAt(100000L);

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.InboxMessageRecord", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.HasKey("ConsumerName", "MessageId")
                        .HasName("pk_ordering_inbox_messages");

                    b.HasIndex("ConsumerName", "ProcessedAtUtc")
                        .HasDatabaseName("ix_ordering_inbox_consumer_processed");

                    b.ToTable("inbox_messages", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_ordering_inbox_consumer_name", "btrim(consumer_name) <> ''");

                            t.HasCheckConstraint("ck_ordering_inbox_message_type", "btrim(message_type) <> ''");

                            t.HasCheckConstraint("ck_ordering_inbox_payload_hash", "char_length(payload_hash) = 64");

                            t.HasCheckConstraint("ck_ordering_inbox_processed_time", "processed_at_utc >= received_at_utc");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderLineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_amount");

                    b.HasKey("Id")
                        .HasName("pk_order_lines");

                    b.HasIndex("OrderId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_order_lines_order_id_position");

                    b.ToTable("order_lines", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_lines_currency", "char_length(currency) = 3");

                            t.HasCheckConstraint("ck_order_lines_position", "position >= 0");

                            t.HasCheckConstraint("ck_order_lines_product_name_not_blank", "btrim(product_name) <> ''");

                            t.HasCheckConstraint("ck_order_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_order_lines_sku_not_blank", "btrim(sku_code) <> ''");

                            t.HasCheckConstraint("ck_order_lines_unit_price", "unit_price_amount >= 0");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_order_number");

                    b.ToTable("orders", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_orders_order_number_not_blank", "btrim(order_number) <> ''");

                            t.HasCheckConstraint("ck_orders_status", "status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRequestRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("IdempotencyKey")
                        .HasName("pk_order_requests");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_order_requests_order_id");

                    b.ToTable("order_requests", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_requests_idempotency_key_not_blank", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_order_requests_request_fingerprint", "char_length(request_fingerprint) = 64");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("DeliveryAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("delivery_attempt_count");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_token");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.HasKey("MessageId")
                        .HasName("pk_ordering_outbox_messages");

                    b.HasIndex("AvailableAtUtc", "LockedUntilUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_ordering_outbox_due")
                        .HasFilter("published_at_utc IS NULL");

                    b.ToTable("outbox_messages", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_ordering_outbox_attempt_shape", "(delivery_attempt_count = 0 AND last_attempt_at_utc IS NULL) OR (delivery_attempt_count > 0 AND last_attempt_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_ordering_outbox_available_time", "available_at_utc >= occurred_at_utc");

                            t.HasCheckConstraint("ck_ordering_outbox_delivery_attempt_count", "delivery_attempt_count >= 0");

                            t.HasCheckConstraint("ck_ordering_outbox_lock_shape", "(lock_token IS NULL AND locked_until_utc IS NULL) OR (lock_token IS NOT NULL AND locked_until_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_ordering_outbox_lock_time", "locked_until_utc IS NULL OR last_attempt_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_ordering_outbox_message_type", "btrim(message_type) <> ''");

                            t.HasCheckConstraint("ck_ordering_outbox_published_not_locked", "published_at_utc IS NULL OR (lock_token IS NULL AND locked_until_utc IS NULL)");

                            t.HasCheckConstraint("ck_ordering_outbox_published_time", "published_at_utc IS NULL OR published_at_utc >= occurred_at_utc");
                        });
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderLineRecord", b =>
                {
                    b.HasOne("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRequestRecord", b =>
                {
                    b.HasOne("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", null)
                        .WithOne()
                        .HasForeignKey("Switchyard.Ordering.Infrastructure.Persistence.OrderRequestRecord", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Switchyard.Ordering.Infrastructure.Persistence.OrderRecord", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
