<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Switchyard.IntegrationContracts\Switchyard.IntegrationContracts.csproj" />
    <ProjectReference Include="..\Switchyard.Messaging\Switchyard.Messaging.csproj" />
    <ProjectReference Include="..\Switchyard.Ordering.Domain\Switchyard.Ordering.Domain.csproj" />
  </ItemGroup>
</Project>
