// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchyard.Inventory.Infrastructure.Persistence;

#nullable disable

namespace Switchyard.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260924094149_AddInventoryMessaging")]
    partial class AddInventoryMessaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Switchyard.Inventory.Infrastructure.Persistence.InventoryInboxMessageRecord", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.HasKey("ConsumerName", "MessageId")
                        .HasName("pk_inventory_inbox_messages");

                    b.HasIndex("ConsumerName", "ProcessedAtUtc")
                        .HasDatabaseName("ix_inventory_inbox_consumer_processed");

                    b.ToTable("inbox_messages", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_inbox_consumer_name", "btrim(consumer_name) <> ''");

                            t.HasCheckConstraint("ck_inventory_inbox_message_type", "btrim(message_type) <> ''");

                            t.HasCheckConstraint("ck_inventory_inbox_payload_hash", "char_length(payload_hash) = 64");

                            t.HasCheckConstraint("ck_inventory_inbox_processed_time", "processed_at_utc >= received_at_utc");
                        });
                });

            modelBuilder.Entity("Switchyard.Inventory.Infrastructure.Persistence.InventoryOutboxMessageRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("DeliveryAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("delivery_attempt_count");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_token");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.HasKey("MessageId")
                        .HasName("pk_inventory_outbox_messages");

                    b.HasIndex("AvailableAtUtc", "LockedUntilUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_inventory_outbox_due")
                        .HasFilter("published_at_utc IS NULL");

                    b.ToTable("outbox_messages", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_outbox_attempt_shape", "(delivery_attempt_count = 0 AND last_attempt_at_utc IS NULL) OR (delivery_attempt_count > 0 AND last_attempt_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_outbox_available_time", "available_at_utc >= occurred_at_utc");

                            t.HasCheckConstraint("ck_inventory_outbox_delivery_attempt_count", "delivery_attempt_count >= 0");

                            t.HasCheckConstraint("ck_inventory_outbox_lock_shape", "(lock_token IS NULL AND locked_until_utc IS NULL) OR (lock_token IS NOT NULL AND locked_until_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_inventory_outbox_lock_time", "locked_until_utc IS NULL OR last_attempt_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_inventory_outbox_message_type", "btrim(message_type) <> ''");

                            t.HasCheckConstraint("ck_inventory_outbox_published_not_locked", "published_at_utc IS NULL OR (lock_token IS NULL AND locked_until_utc IS NULL)");

                            t.HasCheckConstraint("ck_inventory_outbox_published_time", "published_at_utc IS NULL OR published_at_utc >= occurred_at_utc");
                        });
                });

            modelBuilder.Entity("Switchyard.Inventory.Infrastructure.Persistence.ReservationRequestRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("ReleaseReason")
                        .HasColumnType("integer")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.HasKey("RequestId")
                        .HasName("pk_inventory_reservation_requests");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_reservation_id");

                    b.HasIndex("Outcome", "ReleasedAtUtc", "ExpiredAtUtc", "ExpiresAtUtc")
                        .HasDatabaseName("ix_inventory_active_reservation_expiry");

                    b.ToTable("reservation_requests", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservation_expiry_time", "expired_at_utc IS NULL OR expired_at_utc >= requested_at_utc");

                            t.HasCheckConstraint("ck_inventory_reservation_outcome", "outcome IN (0, 1)");

                            t.HasCheckConstraint("ck_inventory_reservation_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_inventory_reservation_release_reason", "release_reason IS NULL OR release_reason IN (0, 1)");

                            t.HasCheckConstraint("ck_inventory_reservation_release_time", "released_at_utc IS NULL OR released_at_utc >= requested_at_utc");

                            t.HasCheckConstraint("ck_inventory_reservation_shape", "(outcome = 0 AND reservation_id IS NOT NULL AND expires_at_utc IS NOT NULL AND ((released_at_utc IS NULL AND release_reason IS NULL AND expired_at_utc IS NULL) OR (released_at_utc IS NOT NULL AND release_reason IS NOT NULL AND expired_at_utc IS NULL) OR (released_at_utc IS NULL AND release_reason IS NULL AND expired_at_utc IS NOT NULL))) OR (outcome = 1 AND reservation_id IS NULL AND expires_at_utc IS NULL AND released_at_utc IS NULL AND release_reason IS NULL AND expired_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_inventory_reservation_sku_not_blank", "btrim(sku_code) <> ''");
                        });
                });

            modelBuilder.Entity("Switchyard.Inventory.Infrastructure.Persistence.StockItemRecord", b =>
                {
                    b.Property<string>("SkuCode")
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.Property<int>("OnHandQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand_quantity");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.HasKey("SkuCode")
                        .HasName("pk_inventory_stock_items");

                    b.ToTable("stock_items", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_stock_on_hand", "on_hand_quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_stock_reserved", "reserved_quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_stock_reserved_not_over_on_hand", "reserved_quantity <= on_hand_quantity");

                            t.HasCheckConstraint("ck_inventory_stock_sku_not_blank", "btrim(sku_code) <> ''");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
