<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Switchyard.Ordering.Application\Switchyard.Ordering.Application.csproj" />
    <ProjectReference Include="..\Switchyard.Ordering.Infrastructure\Switchyard.Ordering.Infrastructure.csproj" />
    <ProjectReference Include="..\Switchyard.Inventory.Infrastructure\Switchyard.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\Switchyard.Payments.Infrastructure\Switchyard.Payments.Infrastructure.csproj" />
  </ItemGroup>
</Project>
